#!/usr/bin/env python2

import argparse
from morpho_complexity import resize

if __name__ == '__main__':
    import os
    import sys

    arg_parser = argparse.ArgumentParser(prog="image_sizes",
            description="resize images to 50,000 pixels in area")
    arg_parser.add_argument('-i',dest='input',
            required=True,
            help="where are the images")
    arg_parser.add_argument('-o',dest='output',
            required=True,
            help="where to save")

    args = arg_parser.parse_args(sys.argv[1:])

    the_dir = args.input
    try:
        os.path.isdir(the_dir)
    except:
        print "give me a real dir please"
        sys.exit(1)

    try:
        os.path.isdir(args.output)
    except:
        print "give me a real output dir please"
        sys.exit(1)

    tmp = [os.path.join(the_dir, image_file) for image_file in os.listdir(the_dir)]
    for filename in tmp:
        if '.tif' in filename:
            output_file = os.path.splitext(filename)[0] + "_resized.tif"
            print "input: {}".format(filename)

            img = Image.open(filename)
            image = misc.fromimage(img, flatten=1)

            new_image = resize.main(image, 128)
            misc.imsave(output_file, new_image)
            print "output: {}".format(output_file)
